apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  labels:
    name: locust
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      name: locust
      role: master
  template:
    metadata:
      labels:
        name: locust
        role: master
    spec:
      containers:
      - name: locust
        image: yatzek/locust:0.8.1
        env:
        - name: LOCUST_SCRIPT
          value: /locust-tasks/tasks.py
        - name: LOCUST_MODE
          value: master
        - name: TARGET_HOST
          value: http://locust-app-svc #http://locust-app-svc.locust.svc.cluster.local
        volumeMounts:
        - name: locust-tasks
          mountPath: /locust-tasks/
        ports:
        - name: loc-master-web
          containerPort: 8089
          protocol: TCP
        - name: loc-master-p1
          containerPort: 5557
          protocol: TCP
        - name: loc-master-p2
          containerPort: 5558
          protocol: TCP
#        resources:
#          limits:
#            cpu: 100m
#            memory: 128Mi
#          requests:
#            cpu: 100m
#            memory: 128Mi
      volumes:
      - name: locust-tasks
        configMap:
          name: locust-tasks
---
kind: Service
apiVersion: v1
metadata:
  name: locust-master
  labels:
    name: locust
    role: master
spec:
  selector:
    name: locust
    role: master
  type: NodePort
  ports:
  - port: 8089
    targetPort: loc-master-web
    protocol: TCP
    name: loc-master-web
  - port: 5557
    targetPort: loc-master-p1
    protocol: TCP
    name: loc-master-p1
  - port: 5558
    targetPort: loc-master-p2
    protocol: TCP
    name: loc-master-p2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  labels:
    name: locust
    role: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      name: locust
      role: worker
  template:
    metadata:
      labels:
        name: locust
        role: worker
    spec:
      containers:
      - name: locust
        image: yatzek/locust:0.8.1
        env:
        - name: LOCUST_SCRIPT
          value: /locust-tasks/tasks.py
        - name: LOCUST_MODE
          value: worker
        - name: LOCUST_MASTER
          value: locust-master #http://locust-master.locust.svc.cluster.local
        - name: LOCUST_MASTER_WEB
          value: "8089"
        - name: TARGET_HOST
          value: http://locust-app-svc #http://locust-app-svc.locust.svc.cluster.local
        volumeMounts:
        - name: locust-tasks
          mountPath: /locust-tasks/
#        resources:
#          limits:
#            cpu: 100m
#            memory: 128Mi
#          requests:
#            cpu: 100m
#            memory: 128Mi
      volumes:
      - name: locust-tasks
        configMap:
          name: locust-tasks
